// User-supplied registration links. Keep these separate from the report-generated data.
window.SUPPLEMENTAL_SITES = [
  {
    id: "aff-workbuddy",
    name: "WorkBuddy",
    url: "https://www.workbuddy.cn/",
    affiliateUrl: "https://www.workbuddy.cn/events/invite?inviteCode=qqvdaigjlbfjgr0",
    domain: "www.workbuddy.cn",
    group: "福利羊毛",
    category: "工具 / 服务",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "邀请链接注册；下载客户端或使用网页",
    registrationGuide: "通过邀请页分享专属链接；好友点击链接注册并使用产品即可参与活动，具体到账以活动页记录为准。",
    quota: "邀请人首次使用 50 积分；好友 7 日内使用 3 天再得 100；受邀用户注册 2,000 积分；30 日内付费升级双方各 500",
    reachability: "2026-09-06 官网公开活动页可达",
    note: "AI 办公工作台，可写方案、做 PPT、数据分析、生成软件和制作音视频；邀请活动截至 2026-09-30，积分规则和活动期限以页面为准。",
    source: "2026-09-06 WorkBuddy 官网邀请页：邀请人基础 50 积分，好友 7 日内累计使用 3 天额外 100；受邀好友注册 2,000 积分；好友 30 日内首次付费升级个人版，双方各得 500 积分。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    offerLabelOverride: "邀请奖励",
    offerKindOverride: "affiliate",
    ratingOverride: 3,
    recommendationRank: 1,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 官网公开活动页"
  },
  {
    id: "aff-doubao-pro",
    name: "豆包电脑版 Pro",
    url: "https://www.doubao.com/",
    affiliateUrl: "https://www.doubao.com/pc/desktop-fission/pro-trial/invited?inviteCode=FSQTJS7oJT",
    domain: "www.doubao.com",
    group: "福利羊毛",
    category: "工具 / 服务",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "电脑打开邀请页并下载客户端",
    registrationGuide: "必须使用电脑打开邀请页；下载豆包电脑版后按页面提示领取高级权益，具体资格与有效期以邀请页为准。",
    quota: "电脑版 Pro 高级权益试用；具体额度和有效期以邀请页为准",
    reachability: "用户提供；邀请页未能由 Searchix 抓取",
    note: "这是面向终端用户的豆包电脑版 Pro 邀请试用入口，不是通用 API 站点；请使用电脑打开并完成客户端下载。",
    source: "用户补充（2026-09-06）：豆包专业版电脑版邀请入口，下载后可免费领取高级权益，需用电脑打开。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    offerLabelOverride: "电脑版 Pro 试用",
    offerKindOverride: "affiliate",
    ratingOverride: 3,
    recommendationRank: 2,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 用户提供；公开页未独立抓取"
  },
  {
    id: "aff-aliyun-aistar",
    name: "阿里云 AI Star",
    url: "https://www.aliyun.com/",
    affiliateUrl: "https://www.aliyun.com/benefit/ai/aistar?userCode=2h6olbzm&clubBiz=subTask..12849120..10274..",
    domain: "www.aliyun.com",
    group: "福利羊毛",
    category: "工具 / 服务",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "活动页登录或注册",
    registrationGuide: "打开 AI Star 活动页，按页面要求登录或注册并领取对应权益；具体资格、产品范围和有效期以活动页为准。",
    quota: "AI 产品 1 亿+ 免费 tokens；部分云产品最长 12 个月试用；邀新奖励最高 1000 元",
    reachability: "2026-09-06 官网公开活动页可达",
    note: "阿里云 AI 权益集合，覆盖千问、DeepSeek、GLM 及图像/视频等多类 AI 产品；不同权益受新客资格、产品和活动规则限制。",
    source: "2026-09-06 阿里云 AI Star 公开页：AI 产品展示 1 亿+ 大模型 tokens 和 30+ 款产品免费体验，部分云产品最长 12 个月试用，邀请好友活动最高 1000 元。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    offerLabelOverride: "AI Star 权益",
    offerKindOverride: "affiliate",
    ratingOverride: 3,
    recommendationRank: 3,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 官网公开活动页"
  },
  {
    id: "aff-columbina",
    name: "Columbina / New API",
    url: "https://newapi.columbina.eu.org/",
    affiliateUrl: "https://newapi.columbina.eu.org/sign-up?aff=YONy",
    domain: "newapi.columbina.eu.org",
    group: "福利羊毛",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "通过邀请链接注册",
    registrationGuide: "通过邀请链接注册；签到金额、倍率和模型库存以控制台当前规则为准。",
    quota: "签到 $100-$200/天；仅 Grok；默认 0.001 倍率",
    reachability: "用户提供；公开注册页未能由 Searchix 抓取",
    note: "仅提供 Grok 模型，默认倍率 0.001；签到 $100-$200 为用户提供信息，未独立核验，建议先用小额请求确认余额、倍率和模型可用性。",
    source: "用户补充（2026-09-06）：Columbina / New API 仅有 Grok 模型，默认 0.001 倍率，签到赠送 $100-$200。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "签到 $100-$200",
    offerKindOverride: "affiliate",
    ratingOverride: 3,
    recommendationRank: 4,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 用户提供；公开页未独立抓取"
  },
  {
    id: "aff-tokenforge",
    name: "TokenForge",
    url: "https://tokenforge.ai.studio/",
    affiliateUrl: "https://tokenforge.ai.studio/sign-up?aff=f0rw",
    domain: "tokenforge.ai.studio",
    group: "精选推荐",
    category: "通用 API",
    status: "closed",
    statusLabel: "当前不可达",
    registration: "邀请链接注册；当前入口打不开",
    registrationGuide: "用户于 2026-09-07 反馈邀请入口打不开；恢复后再按页面规则核对注册、赠额和模型库存。",
    quota: "注册 $90；签到 $20/天；邀请 $40",
    reachability: "用户反馈（2026-09-07）：邀请入口打不开；本轮浏览器虽返回页面标题，但不据此判定服务可用",
    note: "当前入口打不开，已按用户最新反馈隐藏。历史注册 $90、签到 $20/天、邀请 $40 及五家模型支持暂不作为当前推荐，恢复后再核验。",
    source: "用户补充（2026-09-06 至 09-07）：TokenForge 曾报告注册 $90、签到 $20/天、邀请 $40，支持 DeepSeek、xAI、智谱（Z.ai）、Claude 与 OpenAI；2026-09-07 反馈邀请入口打不开。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "注册 $90",
    offerKindOverride: "affiliate",
    ratingOverride: 0,
    browserHidden: true,
    updatedAt: "2026-09-07",
    verified: "2026-09-07 用户反馈；浏览器公开页核验"
  },
  {
    id: "aff-kscsnkli",
    name: "KSC SNKLI AI",
    url: "https://ai.kscsnkli.site/",
    affiliateUrl: "https://ai.kscsnkli.site/sign-up?aff=hc3A",
    domain: "ai.kscsnkli.site",
    group: "公益站",
    category: "通用 API",
    status: "closed",
    statusLabel: "已下架",
    registration: "通过邀请链接注册",
    registrationGuide: "通过邀请链接注册；赠额与模型库存以控制台当前规则为准。",
    quota: "注册 $646,006.31；签到 $6/天",
    reachability: "用户于 2026-09-07 要求下架",
    note: "用户于 2026-09-07 要求下架，不再作为当前可用渠道展示。",
    source: "用户补充（2026-09-07）：要求下掉 KSC SNKLI AI 渠道。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "已下架",
    offerKindOverride: "affiliate",
    ratingOverride: 0,
    browserHidden: true,
    updatedAt: "2026-09-07",
    verified: "2026-09-07 用户补充"
  },
  {
    id: "aff-gorouter",
    name: "GoRouter",
    url: "https://gorouter.app/",
    affiliateUrl: "https://gorouter.app/sign-up?aff=LBpe",
    domain: "gorouter.app",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "GitHub 直接注册",
    registrationGuide: "按注册页提示使用 GitHub 直接完成注册；若遇 Cloudflare 验证，请在普通浏览器完成安全验证。",
    quota: "注册 $120；签到 10 以内",
    pricing: "按次计费：2026-09-05 实测约 $0.30 / 次（可能变动）",
    reachability: "2026-09-05 实测 API 可用，首字延迟约 2.7 秒",
    note: "支持 Claude Opus 4.8、Claude Opus 5 等 Claude 模型；曾发生提示词注入事件，请勿上传敏感内容。按次计费，实测单次成本明显高于同类站点，且不支持 prompt caching；额度、模型和价格以当前页面为准。",
    source: "截图信息：GoRouter 支持 GitHub 直接注册，注册 $120，每日签到 10 以内；参考价格 $0.2-$0.3/次；支持 Claude Opus 4.8、Claude Opus 5、Claude。历史记录曾发生提示词注入事件。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "restricted",
    ratingOverride: 4,
    updatedAt: "2026-09-05",
    verified: "用户补充 + 2026-09-05 实测"
  },
  {
    id: "aff-just-worker",
    name: "JustDoWork",
    url: "https://api.justwoker.icu/",
    affiliateUrl: "https://api.justwoker.icu/sign-up?aff=DcDu",
    domain: "api.justwoker.icu",
    group: "精选推荐",
    category: "通用 API",
    status: "direct",
    statusLabel: "仅 GPT 通道",
    registration: "准备注册满 1 年的 GitHub 账号",
    registrationGuide: "当前浏览器会话已登录并直接进入控制台，未能观察到新用户表单；注册门槛仍以页面实际提示为准。",
    quota: "注册 70 积分；邀请 20 积分；签到 25-30 积分/天",
    pricing: "Opus 5 参考：输入 $0.65/M，输出 $0.65/M；2026-09-05 实测约 $0.0045 / 次（可能变动）",
    reachability: "用户反馈（2026-09-07）：服务已恢复；当前仅有 GPT 通道",
    note: "用户 2026-09-07 反馈已恢复，但当前只有 GPT 通道；历史注册、额度与低成本实测保留，模型库存和长期可用性仍以控制台为准。",
    source: "用户补充（2026-09-06 至 09-07）：JustDoWork 曾无模型，现已恢复但目前只有 GPT 渠道。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    ratingOverride: 4,
    updatedAt: "2026-09-07",
    verified: "2026-09-07 用户反馈"
  },
  {
    id: "aff-agent-router",
    name: "Agent Router",
    url: "https://agentrouter.org/",
    affiliateUrl: "https://agentrouter.org/register?aff=6R2c",
    domain: "agentrouter.org",
    group: "精选推荐",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "准备注册满 1 年的 GitHub 账号",
    registrationGuide: "邀请链接在当前浏览器会话会直接进入控制台；Zcode 已可直连 AG 的全部模型；常见问题参考 https://webnote.cc/p/3198f9008073ff6d。官网公告禁止批量注册、刷量、转售、共享账户或虚假邀请。",
    quota: "注册 50 积分；签到 25 积分/天",
    pricing: "Opus 5 参考：输入 $8/M，输出 $40/M（可能变动）",
    reachability: "用户反馈（2026-09-07）：Agent Router 已恢复；本轮浏览器注册页可达",
    note: "用户 2026-09-07 报告已恢复，重新安排为 5 星；Zcode 已可直连 AG 的全部模型，并增加 Claudeflare 标识；此前 API 被 WAF 拦截是历史故障，模型全量与非浏览器客户端可用性仍应以实际调用为准。",
    source: "用户补充（2026-09-05 至 09-07）：Agent Router 注册 50、重新登录签到 25 积分/天；Opus 5 输入 $8/M、输出 $40/M；2026-09-07 通知称 Zcode 已可直连 AG 全部模型，FAQ：https://webnote.cc/p/3198f9008073ff6d。",
    topicUrls: ["https://webnote.cc/p/3198f9008073ff6d"],
    affiliate: true,
    mainlandAccess: "available",
    ratingOverride: 4,
    updatedAt: "2026-09-07",
    verified: "2026-09-07 用户反馈 + 浏览器公开页核验"
  },
  {
    id: "aff-tabitoken",
    name: "TaBiAI",
    url: "https://tabitoken.com/",
    affiliateUrl: "https://tabitoken.com/sign-up?aff=ZYqh",
    domain: "tabitoken.com",
    group: "公益站",
    category: "通用 API",
    status: "conditional",
    statusLabel: "当前无模型",
    registration: "GitHub 直接注册",
    registrationGuide: "按注册页提示使用 GitHub 直接完成注册；若遇 Cloudflare 验证，请在普通浏览器完成安全验证。",
    quota: "注册 $120；签到随机额度",
    pricing: "2026-09-05 实测约 $0.005 / 次以内（可能变动）",
    reachability: "2026-09-06 模型清单实测：未返回可用模型",
    note: "本轮模型列表为空，暂不作为可用 API 通道展示；不将此结果等同于网站永久关闭。历史注册、额度与价格仅供恢复后复核。",
    source: "用户提供（2026-09-06 API 模型清单实测）：TaBiAI 当前未返回可用模型。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "restricted",
    ratingOverride: 0,
    browserHidden: true,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 用户 API 模型清单实测"
  },
  {
    id: "aff-univibe",
    name: "Univibe",
    url: "https://www.univibe.cc/",
    affiliateUrl: "https://www.univibe.cc/console/auth?type=register&invite=IRPCYQ",
    domain: "www.univibe.cc",
    group: "公益站",
    category: "工具 / 服务",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "邀请链接已预填；需手机号",
    registrationGuide: "当前浏览器会话已登录并进入控制台；邀请链接会预填邀请码。按现有规则，注册需要手机号。",
    quota: "注册 3000 积分；邀请双方各 3000 积分",
    reachability: "LinuxDo 近期独立反馈",
    note: "近期用户反馈积分消耗和价格不透明，且实际效果未达预期；不宜按高价值免费额度推荐。",
    source: "LinuxDo 2026-07-06 反馈帖：用户称消耗 1000+ 积分仍未解决简单问题，另有反馈称积分为黑盒、单价偏高。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    ratingOverride: 2,
    verified: "2026-09-03 LinuxDo 复核"
  },
  {
    id: "aff-moyuu",
    name: "Moyuu",
    url: "https://moyuu.cc/",
    affiliateUrl: "https://moyuu.cc/sign-up?aff=Wi3s",
    domain: "moyuu.cc",
    group: "富可敌国",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "通过邀请链接注册；无签到",
    registrationGuide: "当前浏览器会话已登录并进入控制台，未能观察到新用户表单；平台公告提示长期未充值且无活动账号可能被清理。",
    quota: "注册 $1；后续需充值",
    reachability: "用户补充，未独立复核",
    note: "用户反馈稳定、速度快；需要充值，不适合作为白嫖渠道。",
    source: "用户补充：Moyuu 注册赠 $1，稳定快，需要充值且不能签到。",
    topicUrls: [],
    offerLabelOverride: "需充值",
    offerKindOverride: "paid",
    affiliate: true,
    ratingOverride: 2,
    recommendationRank: 40,
    verified: "用户补充"
  },
  {
    id: "aff-gemai",
    name: "GemAI",
    url: "https://api.gemai.cc/",
    affiliateUrl: "https://api.gemai.cc/sign-up?aff=PKTc",
    domain: "api.gemai.cc",
    group: "精选推荐",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "通过邀请链接注册；具体门槛以注册页为准",
    registrationGuide: "当前浏览器会话已登录并进入控制台，无法从该会话重现新用户表单；点击前请以邀请页实际提示为准。",
    quota: "注册与签到合计 $50",
    reachability: "2026-09-06 API 模型列表实测",
    note: "本轮有效 key 可列出 288 个模型、90 个 Claude；分组前缀包括 [free]、[官B] 至 [官D]、[特价C] 至 [特价F]、[限时福利]，其中有 [free]claude-opus-5。库存规模大，但分组资格、价格与稳定性仍以当前控制台为准。",
    source: "用户提供（2026-09-06 API 模型列表实测）：GemAI 288 个模型、90 个 Claude，含免费、官、特价与限时福利分组。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    ratingOverride: 3,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 用户 API 模型列表实测"
  },
  {
    id: "aff-freemodel",
    name: "FreeModel",
    url: "https://freemodel.dev/",
    affiliateUrl: "https://freemodel.dev/invite/FRE-1a005e60",
    domain: "freemodel.dev",
    group: "精选推荐",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "Google 登录，或 QQ、163 等邮箱验证码注册；无需信用卡",
    registrationGuide: "已验证公开表单：可选 Google 登录，或输入邮箱接收验证码；官网说明完成账号认证即可获得免费 API 额度。",
    quota: "首次充值双方各得 $10",
    reachability: "2026-09-02 Chrome 公开页可达",
    note: "官网支持 OpenAI 与 Anthropic 格式兼容 API；首次充值双方各得 $10 为用户补充，以账单页规则为准。",
    source: "用户补充：FreeModel 邀请链接及首次充值双方各得 $10 规则。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "available",
    offerLabelOverride: "首充双方各 $10",
    offerKindOverride: "affiliate",
    ratingOverride: 2,
    verified: "用户补充 + 2026-09-02 公开页"
  },
  {
    id: "aff-kktoken",
    name: "KKtoken",
    url: "https://kktoken.cc/",
    affiliateUrl: "https://kktoken.cc/sign-up?aff=TmBa",
    domain: "kktoken.cc",
    group: "精选推荐",
    category: "通用 API",
    status: "direct",
    statusLabel: "限定注册",
    registration: "准备注册满 1 年的 GitHub 账号",
    registrationGuide: "邀请入口当前可访问，但未独立观察到新用户表单；请准备满 1 年的 GitHub 账号，并以注册页实际提示为准。",
    quota: "注册 75 + 邀请 25；签到 20 积分/天",
    pricing: "Opus 5 参考：输入 $1/M，输出 $1/M；2026-09-05 实测约 $0.06 / 次（可能变动）",
    reachability: "2026-09-05 实测 API 可用，首字延迟约 2.7 秒",
    note: "货架上比同类站点多出 claude-opus-4-8 与 claude-opus-4-8-thinking 两个档位，但 2026-09-05 实测请求 thinking 档位时返回的 model 字段仍是 claude-opus-5，即上游只有一个模型、档位为站方自行标注。实测单次成本约为最低一档的十余倍。动态赠额、签到和模型可用性请以控制台当前规则为准。",
    source: "用户补充：KKtoken GitHub 账号需满 1 年；注册 75、邀请 25、签到 20 积分/天；Opus 5 输入/输出均 $1/M。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "restricted",
    ratingOverride: 4,
    updatedAt: "2026-09-05",
    verified: "用户补充 + 2026-09-05 实测"
  },
  {
    id: "aff-seekai",
    name: "SeekAi",
    url: "https://seekai.cc/",
    affiliateUrl: "https://seekai.cc/sign-up?aff=lQMF",
    domain: "seekai.cc",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "GitHub 直接注册",
    registrationGuide: "按注册页提示使用 GitHub 直接完成注册；若遇 Cloudflare 验证，请在普通浏览器完成安全验证。",
    quota: "注册 $200",
    pricing: "Opus 5 参考：输入 $5/M，输出 $25/M，缓存 $0.5/M（可能变动）",
    reachability: "2026-09-05 实测 Claude 系全部 502：三轮测试（连续、间隔 16 秒、冷却 70 秒）均失败，25 分钟内未恢复，响应体为裸 502 且无 API 层错误信息",
    note: "2026-09-05 实测：货架列出 claude-opus-5、claude-fable-5、claude-sonnet-5、claude-opus-4-8，但 Claude 系请求全部 502，其中一次等待上游超时约 13.8 秒；能连通的 deepseek-v4-pro-0813 自报上游为第三方服务商。另有限流：每分钟最多 5 次请求，失败次数也计入。注册额度虽高，但当前不建议作为 Claude 通道使用。",
    source: "截图信息：SeekAi 支持 GitHub 直接注册，注册 $200；支持多模型和 API 接入。",
    topicUrls: [],
    affiliate: true,
    mainlandAccess: "restricted",
    ratingOverride: 2,
    updatedAt: "2026-09-05",
    verified: "用户补充 + 2026-09-05 实测"
  },
  {
    id: "pcore-ai",
    name: "pcore.ai",
    url: "https://pcore.ai/",
    affiliateUrl: "https://pcore.ai/sign-up?aff=VIjy",
    domain: "pcore.ai",
    group: "富可敌国",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接进入",
    registration: "官网注册，具体规则以当前页面为准",
    quota: "按站内套餐 / 价格使用",
    reachability: "用户补充，未独立复核",
    note: "用户反馈全模型支持、企业级稳定，可承接 CCMax 蒸馏；未独立复核。",
    source: "用户补充：pcore.ai 全模型支持、企业级稳定，可承接 CCMax 蒸馏；按站内套餐 / 价格使用。",
    topicUrls: [],
    offerLabelOverride: "付费使用",
    offerKindOverride: "paid",
    affiliate: true,
    ratingOverride: 2,
    recommendationRank: 21,
    verified: "用户补充"
  },
  {
    id: "aff-lconai",
    name: "LconAI",
    url: "https://s.lconai.com/",
    affiliateUrl: "https://s.lconai.com/register?aff=hbL5",
    domain: "s.lconai.com",
    group: "高级推广",
    category: "通用 API",
    status: "conditional",
    statusLabel: "待核",
    registration: "通过邀请链接注册；具体身份门槛和注册开放状态待核",
    quota: "用户提供邀请链接，未提供可核实的赠额或签到规则",
    reachability: "用户补充，未独立复核",
    note: "仅收到邀请注册链接，尚未提供站点名称、额度、模型或长期可用性证据。",
    source: "用户补充：LconAI 邀请注册链接。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    ratingOverride: 2,
    recommendationRank: 27,
    verified: "用户补充"
  },
  {
    id: "aff-nova",
    name: "Nova AI",
    url: "https://nova.vcrauo.com/",
    affiliateUrl: "https://nova.vcrauo.com/sign-up?aff=VUHv",
    domain: "nova.vcrauo.com",
    group: "高级推广",
    category: "通用 API",
    status: "conditional",
    statusLabel: "有条件",
    registration: "通过邀请链接注册；进 QQ、TG 或 Discord 任一官方群可领取一次试用周卡",
    registrationGuide: "邀请注册双方各得 1U；群福利、邀请人数和账户风控规则以站内/群公告为准。",
    quota: "邀请注册双方各得 1U；进官方群任一群可领一次 10U 周卡；每邀请 20 名真实注册用户可申请 10U 日卡",
    reachability: "用户补充，未独立复核",
    note: "首次充值优惠已改为抽奖转盘；免费号池分组和国产免费分组处于开放说明中，不提供 Luna 模型。邀请返利为前 20 笔被邀充值金额的 5%。",
    source: "用户补充：Nova AI 邀请注册、群试用周卡、邀请日卡、抽奖和返利规则。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请双方各 1U",
    offerKindOverride: "affiliate",
    ratingOverride: 3,
    recommendationRank: 45,
    verified: "用户补充"
  },
  {
    id: "aff-vibe-code",
    name: "SharedChat",
    url: "https://new.sharedchat.cc/",
    affiliateUrl: "https://new.sharedchat.cc/list/#/register?i=cjaA6",
    domain: "new.sharedchat.cc",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "直接注册",
    quota: "每日签到 $100 额度",
    reachability: "截图信息，未独立复核",
    note: "提供 GPT 模型；必须使用 ChatGPT 客户端或 Codex 客户端，以当前签到到账和模型可用性为准。",
    source: "用户补充（2026-09-06）：new.sharedchat.cc 每日签到 $100，提供 GPT 模型；必须使用 ChatGPT 客户端或 Codex 客户端。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    mainlandAccess: "available",
    ratingOverride: 4,
    updatedAt: "2026-09-03",
    verified: "2026-09-06 用户补充"
  },
  {
    id: "aff-gls-api",
    name: "GLS API",
    url: "https://fxqidian.de5.net/",
    affiliateUrl: "https://fxqidian.de5.net/sign-up?aff=NHII",
    domain: "fxqidian.de5.net",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "直接注册",
    quota: "注册 $10；每日签到 $10 以内",
    reachability: "截图信息，未独立复核",
    note: "纯公益站，支持 API；适合日常 API 接入和轻量调用。",
    source: "截图信息：GLS API 可直接注册，注册 $10，每日签到 $10 以内，支持 API。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    ratingOverride: 4,
    updatedAt: "2026-09-03",
    verified: "用户补充"
  },
  {
    id: "aff-yesnovelai",
    name: "YesNovelAI",
    url: "https://nai.rinko.ai/",
    affiliateUrl: "https://nai.rinko.ai/sign-up?aff=5FzR",
    domain: "nai.rinko.ai",
    group: "公益站",
    category: "生图 / 视频",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "直接注册",
    quota: "注册 $150；每日签到 $32",
    reachability: "截图信息，未独立复核",
    note: "这是绘图站点，不是通用文本模型 API：专注于 NovelAI 图像生成，支持文生图、图生图、局部重绘、Vibe Transfer 与角色参考，并提供原生 NovelAI、YesNAI 兼容及 OpenAI Images API。",
    source: "2026-09-06 官网公开页：YesNovelAI 专注于 NovelAI 图像生成，提供文生图、图生图、局部重绘、Vibe Transfer、角色参考和绘图 API；注册与签到额度仍以当前控制台为准。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    ratingOverride: 4,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 官网公开页"
  },
  {
    id: "aff-nailao-api",
    name: "奶酪 API",
    url: "https://nailao.biz/",
    affiliateUrl: "https://nailao.biz/sign-up?aff=uz3a",
    domain: "nailao.biz",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "直接注册；QQ 群签到",
    quota: "注册 $10.5；QQ 群每日签到 $2 以内",
    reachability: "截图信息，未独立复核",
    note: "公益中转站，支持 DeepSeek-V4-Flash 等主流模型；签到需在 QQ 群完成。",
    source: "截图信息：奶酪 API 可直接注册，注册 $10.5，QQ 群每日签到约 $2 以内；支持 DeepSeek-V4-Flash 等主流模型。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    ratingOverride: 4,
    updatedAt: "2026-09-03",
    verified: "用户补充"
  },
  {
    id: "aff-futureppo",
    name: "Future Hub",
    url: "https://api.futureppo.top/",
    affiliateUrl: "https://api.futureppo.top/register?aff=7CL2GWV7WRG93VAE",
    domain: "api.futureppo.top",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "GitHub 满 5 年老号，或 edu.cn 邮箱、LINUX DO 账号注册",
    quota: "注册 100+ 额度；每日签到 50 额度",
    reachability: "截图信息，未独立复核",
    note: "支持 GPT、DeepSeek、GLM 5.2、MiniMax；GitHub 路径要求 5 年老号，edu.cn 与 LINUX DO 可走替代注册方式。",
    source: "用户补充（2026-09-03）：Future Hub 支持 GitHub 满 5 年老号、edu.cn 邮箱或 LINUX DO 注册；注册 100+ 额度、每日签到 50 额度，提供 GPT、DeepSeek、GLM 5.2、MiniMax。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "邀请入口",
    offerKindOverride: "unknown",
    ratingOverride: 4,
    updatedAt: "2026-09-03",
    verified: "2026-09-03 用户补充"
  },
  {
    id: "aff-motomoto",
    name: "MotoMoto",
    url: "https://motomoto.lol/",
    affiliateUrl: "https://motomoto.lol/sign-up?aff=Xq7Z",
    domain: "motomoto.lol",
    group: "公益站",
    category: "通用 API",
    status: "closed",
    statusLabel: "已下架",
    registration: "邮箱通过邀请链接注册；控制台创建令牌",
    registrationGuide: "创建令牌后使用 Base URL https://motomoto.lol/v1；数据授权的当天签到额度更高。",
    quota: "注册约 $30；普通签到约 $10/天；数据授权当天约 $50；邀请奖励未到账",
    reachability: "用户于 2026-09-07 要求下架",
    note: "用户于 2026-09-07 要求下架，不再作为当前可用渠道展示。",
    source: "用户补充（2026-09-07）：要求下掉 MotoMoto 渠道。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "已下架",
    offerKindOverride: "unknown",
    ratingOverride: 0,
    browserHidden: true,
    updatedAt: "2026-09-07",
    verified: "2026-09-07 用户补充"
  },
  {
    id: "aff-onekeyallmodels",
    name: "OneKeyAllModels",
    url: "https://www.onekeyallmodels.com/",
    affiliateUrl: "https://www.onekeyallmodels.com/register?aff=WP8BXDTR6UF8",
    domain: "www.onekeyallmodels.com",
    group: "高级推广",
    category: "通用 API",
    status: "conditional",
    statusLabel: "需条件",
    registration: "邀请链接注册；联系 QQ 群客服领取新手卡",
    registrationGuide: "加入 QQ 群 1107261739（二群）联系客服，领取 Codex 新手入门卡。",
    quota: "联系客服领取一张 Codex 新手入门卡 $20",
    reachability: "用户补充，未独立复核",
    note: "仅确认社群领取的 Codex 新手卡；未提供常规注册赠额、签到或完整模型清单。",
    source: "用户补充（2026-09-03）：QQ 群联系客服赠送 Codex 新手入门卡 $20。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "社群领 $20",
    offerKindOverride: "affiliate",
    ratingOverride: 2,
    verified: "2026-09-03 用户补充"
  },
  {
    id: "aff-tokenrhythm",
    name: "Token Rhythm",
    url: "https://tokenrhythm.studio/",
    affiliateUrl: "https://tokenrhythm.studio/i/rf_tr_mjXNiigCJYmurynQ_MfSIg69",
    domain: "tokenrhythm.studio",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "邀请链接注册；邀请后双方需用 OpenSquilla 完成一次调用",
    registrationGuide: "通过邀请链接注册后，被邀请用户下载 OpenSquilla 客户端并完成一次调用，双方才会触发邀请奖励。",
    quota: "注册 68 额度；邀请奖励金额未公开",
    reachability: "用户补充，未独立复核",
    note: "文档称 DeepSeek-V4-Pro-0831、GLM 5.2、Qwen 3.8 可用；邀请奖励须完成客户端调用，不能按普通拉新直接承诺。",
    source: "用户补充（2026-09-03）：Token Rhythm 注册 68 额度与 OpenSquilla 邀请触发规则。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "注册 68",
    offerKindOverride: "affiliate",
    ratingOverride: 4,
    verified: "2026-09-03 用户补充"
  },
  {
    id: "aff-fuka-api",
    name: "Fuka API",
    url: "https://api.fuka.win/",
    affiliateUrl: "https://api.fuka.win/sign-up?aff=YM5F",
    domain: "api.fuka.win",
    group: "公益站",
    category: "通用 API",
    status: "conditional",
    statusLabel: "需条件",
    registration: "邀请链接注册；仅支持 QQ 邮箱验证",
    quota: "注册 100 点；邀请双方各得 50 点",
    reachability: "用户补充，未独立复核",
    note: "支持 Anthropic、Google、OpenAI、DeepSeek、智谱；未提供签到或点数换算规则。",
    source: "用户补充（2026-09-03）：Fuka API 仅开放 QQ 邮箱验证，注册 100 点、邀请双方各得 50 点；支持 Anthropic、Google、OpenAI、DeepSeek、智谱。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "双方各 50 点",
    offerKindOverride: "affiliate",
    ratingOverride: 4,
    verified: "2026-09-03 用户补充"
  },
  {
    id: "aff-juziai",
    name: "聚智 AI",
    url: "https://api.juziai.cc/",
    affiliateUrl: "https://api.juziai.cc/sign-up?aff=hrOe",
    domain: "api.juziai.cc",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "QQ 邮箱注册",
    quota: "注册 $100；累计调用满 5 次自动签到，每次 5-20",
    reachability: "用户补充，未独立复核",
    note: "文档称可用 DeepSeek-V4-Pro-0831、GLM 5.2、Qwen 3.8；自动签到需先累计 5 次调用。",
    source: "用户补充（2026-09-03）：聚智 AI QQ 邮箱、注册 $100、调用门槛与自动签到规则。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "注册 $100",
    offerKindOverride: "affiliate",
    ratingOverride: 4,
    verified: "2026-09-03 用户补充"
  },
  {
    id: "aff-api520",
    name: "API520",
    url: "https://api520.pro/",
    affiliateUrl: "https://api520.pro/register?aff=PKli",
    domain: "api520.pro",
    group: "公益站",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "QQ 邮箱注册",
    quota: "注册 100 次试用；邀请双方各得 100 次",
    reachability: "2026-09-06 API 模型列表实测",
    note: "本轮有效 key 可列出 142 个模型、62 个 Claude。站方在模型名中直接标注官方、限时官 key、逆向和 Kiro 转售来源；这提高了渠道透明度，但标作逆向的线路可能随时中断。额度单位仍为调用次数。",
    source: "用户提供（2026-09-06 API 模型列表实测）：API520 142 个模型、62 个 Claude；模型名自标官方、限时官 key、逆向与 Kiro 转售来源。",
    topicUrls: [],
    affiliate: true,
    offerLabelOverride: "注册 100 次",
    offerKindOverride: "affiliate",
    ratingOverride: 4,
    updatedAt: "2026-09-06",
    verified: "2026-09-06 用户 API 模型列表实测"
  },
  {
    id: "aff-tencent-wego",
    name: "腾讯开发者小程序活动",
    url: "https://chatapi.weixin.qq.com/wego/weastraaiweb/token",
    domain: "chatapi.weixin.qq.com",
    group: "福利羊毛",
    category: "工具 / 服务",
    status: "conditional",
    statusLabel: "需条件",
    registration: "官网注册路径待定位；同源 /register 于 2026-09-09 返回 404；活动申请规则需以当前入口为准",
    registrationGuide: "本轮公开检查未找到有效注册表单：同源 /register 返回 HTTP 404；不要把 token 接口地址当成注册入口。",
    quota: "GLM 5.2、DeepSeek-V4-Flash 免费调用",
    reachability: "用户截图，未独立复核",
    note: "一次仅开一个会话；多人/多会话容易报错，适合作为受限的开发者活动体验。本轮检查同源 /register 返回 404，注册/申请入口需重新定位。",
    source: "用户截图（2026-09-03）：腾讯开发者小程序活动提供 GLM 5.2、DeepSeek-V4-Flash 免费调用，需排队审核且单会话使用；Chrome 公开注册路径检查（2026-09-09）：同源 /register 返回 HTTP 404。",
    topicUrls: [],
    offerLabelOverride: "免费调用",
    offerKindOverride: "free",
    ratingOverride: 3,
    verified: "2026-09-09 Chrome 注册路径检查；2026-09-03 用户截图"
  },
  {
    id: "aff-sensenova",
    name: "商汤日日新",
    url: "https://www.sensenova.cn/",
    domain: "www.sensenova.cn",
    group: "福利羊毛",
    category: "通用 API",
    status: "direct",
    statusLabel: "可直接注册",
    registration: "公开注册",
    quota: "公测免费 SenseNova-6.8-Flash-Lite、DeepSeek-V4-Flash；按 Token 消耗",
    reachability: "用户截图，未独立复核",
    note: "8 月 28 日起改为按 Token 消耗，不再按调用次数限制；用户反馈适合作为多模型兜底。",
    source: "用户截图（2026-09-03）：商汤日日新公测免费 SenseNova-6.8-Flash-Lite、DeepSeek-V4-Flash，8 月 28 日改按 Token 消耗。",
    topicUrls: [],
    offerLabelOverride: "公测免费模型",
    offerKindOverride: "free",
    ratingOverride: 4,
    verified: "2026-09-03 用户截图"
  },
  {
    id: "aff-zero-zero",
    name: "0-0",
    url: "https://0-0.pro/",
    affiliateUrl: "https://0-0.pro/register?ref=52423BD8",
    domain: "0-0.pro",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册；按控制台套餐使用", quota: "付费站；资源页称支持 Codex、Claude Code、Gemini CLI",
    reachability: "用户确认可访问", note: "长期付费中转；支持 Codex、Claude Code、Gemini CLI，按控制台套餐使用。",
    source: "聚合AI公益站 2026-09-04：0-0.pro 支持 Codex、Claude Code、Gemini CLI，标注长期稳定。", topicUrls: [], affiliate: true,
    offerLabelOverride: "付费 / 0.03", offerKindOverride: "paid", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-token-harbor",
    name: "Token API",
    url: "https://token.xn--cjz.space/",
    affiliateUrl: "https://token.xn--cjz.space/register?aff=FYRWDGFKKQNV",
    domain: "token.xn--cjz.space",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册", quota: "当前邀请链接充值返利 16.6%（可提现）；Plus 0.08、Kiro 0.18",
    reachability: "用户确认可访问", note: "可通过邮箱注册；充值返利和可用性以控制台当期规则为准。",
    source: "聚合AI公益站 2026-09-04：Token API 价格、可用性和邀请充值返利说明。", topicUrls: [], affiliate: true,
    offerLabelOverride: "充值返利 16.6%", offerKindOverride: "affiliate", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-universe-federation",
    name: "Universe Federation",
    url: "https://api.wapq.cn/",
    affiliateUrl: "https://api.wapq.cn/register?aff=DGBo",
    domain: "api.wapq.cn",
    group: "公益站", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册", quota: "当前邀请链接注册可获初始额度；具体数额未公开",
    reachability: "用户确认可访问", note: "初始额度需经邀请入口获得；具体数额以注册后控制台为准。",
    source: "聚合AI公益站 2026-09-04：Universe Federation 邀请注册才有初始额度。", topicUrls: [], affiliate: true,
    offerLabelOverride: "邀请得初始额度", offerKindOverride: "affiliate", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-aerolink",
    name: "aerolink",
    url: "https://aerolink.lat/",
    affiliateUrl: "https://aerolink.lat/register?ref=ME224ZO",
    domain: "aerolink.lat",
    group: "公益站", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册", quota: "官网新账户免费 $35；含 1 周 Starter",
    reachability: "官网首页 2026-09-04 可访问", note: "一把 API Key 面向各类 AI agent；免费权益按官网当前新用户规则发放。",
    source: "官网首页 2026-09-04：新账户免费 $35，含 1 周 Starter。", topicUrls: [], affiliate: true,
    offerLabelOverride: "新用户免费 $35", offerKindOverride: "signup", ratingOverride: 4, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；官网页复核"
  },
  {
    id: "aff-dawcode",
    name: "DawCode",
    url: "https://dawcode.com/",
    affiliateUrl: "https://dawcode.com/sign-up?aff=sbcb",
    domain: "dawcode.com",
    group: "公益站", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册（QQ 邮箱可用）", quota: "资源页称注册 $5；签到 $0-$1/天",
    reachability: "用户确认可访问", note: "QQ 邮箱可注册；签到金额按控制台当期规则发放。",
    source: "聚合AI公益站 2026-09-04：DawCode QQ 邮箱注册、$5 注册额与 $0-$1 签到说明。", topicUrls: [], affiliate: true,
    offerLabelOverride: "注册 $5", offerKindOverride: "signup", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-worldclawpro",
    name: "WorldClawPro",
    url: "https://worldclawpro.ai/",
    affiliateUrl: "https://worldclawpro.ai/sign-up?aff=Xkkg",
    domain: "worldclawpro.ai",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册；付费使用", quota: "资源页标注 0.03 倍率；未见免费额度规则",
    reachability: "用户确认可访问", note: "付费 API 中转；提供 QQ/TG 社群入口，按控制台套餐使用。",
    source: "聚合AI公益站 2026-09-04：WorldClawPro 0.03 倍率与社群服务入口。", topicUrls: [], affiliate: true,
    offerLabelOverride: "付费 / 0.03", offerKindOverride: "paid", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-bluesminds",
    name: "Bluesminds",
    url: "https://api.bluesminds.com/",
    affiliateUrl: "https://api.bluesminds.com/sign-up?aff=n9Pk",
    domain: "api.bluesminds.com",
    group: "公益站", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱注册", quota: "当前邀请链接注册约 $100；约官方价一折",
    reachability: "用户确认可访问", note: "邀请入口可获得初始额度；聚合 API 服务，价格以控制台为准。",
    source: "聚合AI公益站 2026-09-04：Bluesminds 注册约 $100 与价格说明。", topicUrls: [], affiliate: true,
    offerLabelOverride: "注册约 $100", offerKindOverride: "signup", ratingOverride: 4, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-rrr-api",
    name: "RRR API",
    url: "https://rrrapi.com/",
    affiliateUrl: "https://rrrapi.com/sign-up?aff=qVoK",
    domain: "rrrapi.com",
    group: "公益站", category: "通用 API", status: "closed", statusLabel: "已下架",
    registration: "邮箱注册", quota: "新用户 $100；当前邀请链接再加 $10",
    reachability: "用户于 2026-09-07 要求下架", note: "用户要求下架，不再作为当前可用渠道展示。",
    source: "用户补充（2026-09-07）：要求下掉 RRR API 渠道。", topicUrls: [], affiliate: true,
    offerLabelOverride: "已下架", offerKindOverride: "unknown", ratingOverride: 0, browserHidden: true, updatedAt: "2026-09-07", verified: "2026-09-07 用户补充"
  },
  {
    id: "aff-xiaobai-code",
    name: "小白 Code",
    url: "https://token.dialoguedui.com/",
    affiliateUrl: "https://token.dialoguedui.com/register?aff=MR5KEZT6B664",
    domain: "token.dialoguedui.com",
    group: "付费站点", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "邮箱注册；进群、学生证明或发图可领取额外额度", quota: "签到约 $0.25/天；进群 $2；学生证明 $2；发图 $2",
    reachability: "用户确认可访问", note: "支持 Codex、Claude Code、Cursor；额外奖励需进群、学生证明或发图后领取。",
    source: "聚合AI公益站 2026-09-04：小白 Code 签到、社群和学生/发图奖励说明。", topicUrls: [], affiliate: true,
    offerLabelOverride: "签到约 $0.25/天", offerKindOverride: "checkin", ratingOverride: 3, updatedAt: "2026-09-04", verified: "2026-09-04 用户确认；资源页补充"
  },
  {
    id: "aff-iceberg",
    name: "冰山公益站",
    url: "https://iceberg.tiktok.vip/",
    domain: "iceberg.tiktok.vip",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "LINUX DO 信任等级 ≥1；注册需约 $5",
    quota: "帖子称约 $10,000 等效额度/日；5 RPM；注册赠额与社区兑换码规则以当前帖为准",
    reachability: "LinuxDo 2026-09-01 至 09-06 帖子提供；未独立复核",
    note: "额度宣传较高，但有 Linux.do 等级与付费门槛，且长期稳定性、倍率和兑换码规则未独立核验；建议先用小额请求测试。",
    source: "LinuxDo 2026-09-01 帖子 2857132、2026-09-05 更新帖 2860668。",
    topicUrls: ["https://linux.do/t/topic/2857132", "https://linux.do/t/topic/2860668"], affiliate: false,
    offerLabelOverride: "约 $10,000 等效/日", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-mofas",
    name: "魔方公益站",
    url: "https://mofas.one/",
    domain: "mofas.one",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "规则待核",
    registration: "注册方式未在帖子中明确",
    quota: "帖子称约 200 并发；固定注册赠额和签到规则未明确",
    reachability: "LinuxDo 帖子提供；未独立复核",
    note: "目前能确认的主要是模型与并发宣传，注册入口、福利到账和实际并发仍需以站内控制台为准。",
    source: "LinuxDo 2026-09-04 主题 2863101。",
    topicUrls: ["https://linux.do/t/topic/2863101"], affiliate: false,
    offerLabelOverride: "福利待核", offerKindOverride: "unknown", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-noah-daycard",
    name: "Noah 公益日卡",
    url: "https://api-usage.noahxu.site/",
    domain: "api-usage.noahxu.site",
    group: "付费站点", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "购买 LDC 日卡；非长期账号",
    quota: "24 小时有效；约 5 LDC / $5；每日发卡地址可能变化",
    reachability: "LinuxDo 帖子提供；未独立复核",
    note: "这是短期日卡服务，不是长期免费 API；购买前确认当天发卡地址、有效期和模型库存。",
    source: "LinuxDo 2026-09-04 主题 2862187。",
    topicUrls: ["https://linux.do/t/topic/2862187"], affiliate: false,
    offerLabelOverride: "24 小时日卡", offerKindOverride: "paid", ratingOverride: 2, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-zerocat",
    name: "ZeroCat",
    url: "https://zero.cat/",
    domain: "zero.cat",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "站内注册；提交评论 ID；绑定 Telegram",
    quota: "当前活动：连续 7 天、每天免费调用 200 次国产大模型；旧评论 $5 福利与模型价格以控制台为准",
    reachability: "LinuxDo 2026-09-08 主题；未独立 API 核验",
    note: "最新活动帖称连续 7 天每天可免费调用 200 次国产大模型；活动仍依赖站内规则，Claude 等其他模型和余额到账需现场确认。",
    source: "LinuxDo 2026-08-31 主题 2845144；2026-09-08 更新主题 2874321。",
    topicUrls: ["https://linux.do/t/topic/2845144", "https://linux.do/t/topic/2874321"], affiliate: false,
    offerLabelOverride: "7 天 × 200 次（帖子称）", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 抽取 LinuxDo 更新帖"
  },
  {
    id: "aff-dkby",
    name: "星域互联 DKBY",
    url: "https://dkby.com/",
    domain: "dkby.com",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "注册方式未在帖子中明确；回帖用户名后领取活动额度",
    quota: "评论用户名送 $3；专属 Pro 约 0.08 倍率；GPT-6 说法待核",
    reachability: "LinuxDo 帖子提供；未独立复核",
    note: "活动福利需要回帖，GPT-6 和倍率属于帖子信息，实际模型库存、账户规则和稳定性以控制台为准。",
    source: "LinuxDo 2026-08-30 主题 2843933。",
    topicUrls: ["https://linux.do/t/topic/2843933"], affiliate: false,
    offerLabelOverride: "评论送 $3", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-acsgateway",
    name: "ACS Gateway",
    url: "https://acsgw.top/",
    domain: "acsgw.top",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "站内注册；5 元起充；活动需回帖用户 ID / Telegram",
    quota: "新用户回帖用户 ID 送 $2；Telegram 签到；5 元起充；当前活动含 LINUXDO_ACS 9 折码",
    reachability: "LinuxDo 2026-09-07 主题；未独立 API 核验",
    note: "最新主题称已上线 GPT-6 Astra，新用户注册后回帖 ID 可领 $2；充值门槛、退款手续费、倍率和 Telegram 签到规则以当前页面为准，充值前先小额验证。",
    source: "LinuxDo 2026-09-01 主题 2848164；2026-09-07 更新主题 2865614。",
    topicUrls: ["https://linux.do/t/topic/2848164", "https://linux.do/t/topic/2865614"], affiliate: false,
    offerLabelOverride: "GPT-6 Astra；回帖 $2 + 签到", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Chrome 读取 LinuxDo 更新帖"
  },
  {
    id: "aff-token-x",
    name: "Token-X",
    url: "https://token-x.com/",
    domain: "token-x.com",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "规则待核",
    registration: "注册方式未在帖子中明确；邀请和抽奖按当期活动参与",
    quota: "9 月 7 日抽奖已截止；当前注册、邀请和赠额规则待核",
    reachability: "LinuxDo 2026-09-07 活动帖；未独立复核当前福利",
    note: "原活动帖的 10 份 100 元抽奖截止时间为 2026-09-07；不再把已截止抽奖和 $3 邀请奖励展示为当前福利，新的活动需以最新公告为准。",
    source: "LinuxDo 2026-09-06 主题 2863820；活动截止时间为 2026-09-07。",
    topicUrls: ["https://linux.do/t/topic/2863820"], affiliate: false,
    offerLabelOverride: "活动已截止 / 待核", offerKindOverride: "unknown", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 复核活动截止时间"
  },
  {
    id: "aff-ghostinterview",
    name: "GhostInterview",
    url: "https://ghostinterview.co/",
    domain: "ghostinterview.co",
    group: "福利羊毛", category: "工具 / 服务", status: "direct", statusLabel: "可直接注册",
    registration: "开放注册；免费试用，无需信用卡",
    quota: "支持 coding、system design、OOD；试用次数未公开；活动抽 Pro 会员",
    reachability: "LinuxDo 帖子提供；未独立复核",
    note: "技术面试练习工具，不是通用 API；免费试用次数和 Pro 活动资格以产品页面为准。",
    source: "LinuxDo 2026-08-28 主题 2838895。",
    topicUrls: ["https://linux.do/t/topic/2838895"], affiliate: false,
    offerLabelOverride: "免费试用", offerKindOverride: "free", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-apevon",
    name: "Apevon Science",
    url: "https://apevon.ai/",
    domain: "apevon.ai",
    group: "福利羊毛", category: "工具 / 服务", status: "conditional", statusLabel: "内测",
    registration: "教育邮箱或企业邮箱；内测资格审核",
    quota: "Claude / GPT + GPU / CPU 科研执行环境；具体额度未公开",
    reachability: "LinuxDo 帖子提供；未独立复核",
    note: "面向科研任务的 AI 执行环境，不是通用 API；教育或企业邮箱审核更快，内测资格和资源额度以站方为准。",
    source: "LinuxDo 2026-09-02 主题 2855089。",
    topicUrls: ["https://linux.do/t/topic/2855089"], affiliate: false,
    offerLabelOverride: "内测资格", offerKindOverride: "unknown", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 LinuxDo 帖子整理"
  },
  {
    id: "aff-memorax-code",
    name: "MemoraX Code",
    url: "https://code.memorax.net/",
    domain: "code.memorax.net",
    group: "福利羊毛", category: "工具 / 服务", status: "conditional", statusLabel: "规则待核",
    registration: "官网注册路径待定位；同源 /register 于 2026-09-09 返回 404；活动需完成首次安装和激活",
    registrationGuide: "本轮公开检查访问 /register 得到 Error response / HTTP 404，尚未找到可复核的注册表单；不要据此推断活动失效。",
    quota: "新老用户各 $10 API 兑换券；累计邀请最高 $400，具体到账条件以产品规则为准",
    reachability: "V2EX 2026-09-09 主题；官网与注册链接已公开，未独立安装核验",
    note: "这是 Coding Agent 记忆插件，不是通用 API 站。最新帖子称新老用户可得 $10 API 兑换券，邀请奖励需首次安装、激活且保持 1 天活跃；本轮 /register 返回 Error response / HTTP 404，未把最高 $400 当作注册即得。",
    source: "LinuxDo 2026-09-02 主题 2855175；V2EX 2026-09-09 主题 1240581；Chrome 注册路径检查（2026-09-09）：同源 /register 返回 Error response / HTTP 404。",
    topicUrls: ["https://linux.do/t/topic/2855175", "https://www.v2ex.com/t/1240581"], affiliate: false,
    offerLabelOverride: "$10 兑换券 / 邀请最高 $400", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 抽取 V2EX 主题 + Chrome 注册路径检查"
  },
  {
    id: "aff-bai",
    name: "B.AI",
    url: "https://chat.b.ai/",
    affiliateUrl: "https://chat.b.ai/chat?invite_code=7M9DBT",
    domain: "chat.b.ai",
    group: "福利羊毛", category: "工具 / 服务", status: "conditional", statusLabel: "需邀请入口",
    registration: "通过邀请链接访问；登录 / 注册限制未核实",
    quota: "限免：GLM-5.3-Flash、DeepSeek-V4-Flash-Vision-Exp；有效期与次数未公开",
    reachability: "用户提供邀请链接；未独立复核",
    note: "B.AI 网页聊天工具，不是通用 API；限免模型、有效期和使用次数可能随活动变化。",
    source: "用户补充（2026-09-06）：B.AI 邀请入口及 GLM-5.3-Flash、DeepSeek-V4-Flash-Vision-Exp 限免说明。",
    topicUrls: [], affiliate: true,
    offerLabelOverride: "限免模型", offerKindOverride: "free", ratingOverride: 3, updatedAt: "2026-09-06", verified: "2026-09-06 用户补充"
  },
  {
    id: "aff-camel-hub",
    name: "CaMeL AI",
    url: "https://api.camel-hub.cn/",
    affiliateUrl: "https://api.camel-hub.cn/register?aff=TVWG",
    domain: "api.camel-hub.cn",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "需邮箱验证",
    registration: "邀请链接注册；用户名 / 密码；邮箱验证码；需填写邀请码",
    registrationGuide: "注册页可见用户名、密码、邮箱验证码和邀请码字段；邀请入口会预填 TVWG，具体注册限制以页面为准。",
    quota: "当前注册赠额、签到与模型清单未提供",
    reachability: "2026-09-07 浏览器公开页可达；注册表单可见",
    note: "入口能开不等于额度和 API 稳；当前只确认注册表单和邀请参数，模型清单、赠额、签到与接口可用性均待控制台核验。",
    source: "用户补充（2026-09-07）：CaMeL AI 邀请注册链接；本轮浏览器公开页核验可见注册表单。",
    topicUrls: [], affiliate: true,
    registrationTags: ["email", "invite"], benefitTags: ["unknown"],
    benefitDisplay: "当前福利待核",
    offerLabelOverride: "福利待核", offerKindOverride: "unknown", ratingOverride: 3,
    updatedAt: "2026-09-07", verified: "2026-09-07 用户补充 + 浏览器公开页核验"
  },
  {
    id: "aff-aipm",
    name: "AIPM",
    url: "https://emtf.aipm9527.online/",
    affiliateUrl: "https://emtf.aipm9527.online/sign-up?aff=aR3b",
    domain: "emtf.aipm9527.online",
    group: "公益站", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "用户名 / 密码注册；支持 GitHub 或 LinuxDO 登录",
    registrationGuide: "当前注册页可见用户名、密码和确认密码字段，并提供 GitHub、LinuxDO 登录入口；当前是否需要额外审核以页面为准。",
    quota: "历史 Linux.do 帖子曾出现 $200-$1,000 公益额度；当前赠额与签到规则未核实",
    reachability: "2026-09-07 浏览器公开页可达；注册表单可见",
    note: "历史帖子确实发过大额公益 API，但帖子里的额度和模型会随时间失效；当前页面只确认注册入口，模型库存、余额到账和 API 稳定性仍待现场验证。历史福利别当永久白票。",
    source: "用户补充（2026-09-07）：AIPM 邀请注册链接；Searchix 检索到 Linux.do 2026-02-06 至 02-09 历史帖子曾出现 $200、$1,000 公益 API，相关额度和模型不视为当前承诺。",
    topicUrls: ["https://linux.do/t/topic/1575023", "https://linux.do/t/topic/1576990", "https://linux.do/t/topic/1581759", "https://linux.do/t/topic/1585823"],
    affiliate: true,
    registrationTags: ["open", "github", "linuxdo"], benefitTags: ["unknown"],
    benefitDisplay: "历史 $200-$1,000（当前待核）",
    offerLabelOverride: "历史额度待核", offerKindOverride: "unknown", ratingOverride: 3,
    updatedAt: "2026-09-07", verified: "2026-09-07 用户补充 + 浏览器公开页 + Linux.do 历史帖子"
  },
  {
    id: "aff-zebra-api",
    name: "斑马 API",
    url: "https://bmapi.020212.xyz/",
    affiliateUrl: "https://bmapi.020212.xyz/register?aff=G8K663S2U2SQ",
    domain: "bmapi.020212.xyz",
    group: "福利羊毛", category: "通用 API", status: "conditional", statusLabel: "需人机验证",
    registration: "邀请链接注册；邀请码预填；需通过 Cap 人机验证",
    registrationGuide: "注册页会预填邀请码 G8K663S2U2SQ，邮箱和密码字段需先通过 Cap 人机验证后继续；具体注册限制以页面为准。",
    quota: "拉新送 1 小时体验卡；领取对象、到账与可用范围待核",
    reachability: "2026-09-07 浏览器公开页可达；注册页显示 Cap 人机验证",
    note: "拉新福利明确但仍缺少独立到账证据；入口能开不等于体验卡已经到账，先按活动页确认对象、有效期和可用模型。",
    source: "用户补充（2026-09-07）：斑马 API 拉新送 1 小时体验卡；本轮浏览器公开页核验注册页可达并显示 Cap 人机验证。",
    topicUrls: [], affiliate: true,
    registrationTags: ["invite", "unknown"], benefitTags: ["referral"],
    benefitDisplay: "拉新送 1 小时体验卡",
    offerLabelOverride: "拉新 1 小时体验卡", offerKindOverride: "affiliate", ratingOverride: 3,
    recommendationRank: 340,
    updatedAt: "2026-09-07", verified: "2026-09-07 用户补充 + 浏览器公开页核验"
  },
  {
    id: "aff-tokenra",
    name: "TokenRa",
    url: "https://tokenra.io/zh/",
    domain: "tokenra.io",
    group: "付费站点", category: "通用 API", status: "conditional", statusLabel: "注册规则待核",
    registrationUrl: "https://tokenra.io/sign-up",
    registration: "官网公开注册入口；Chrome 2026-09-09 复核可打开 /sign-up 但未取得注册表单，邮箱/账号条件待页面完整加载后核验",
    registrationGuide: "公开首页可见“注册”和“立即注册”；本轮真实 /sign-up 页面可达但未取得表单，未提交注册。",
    quota: "按量计费；官网公开模型价格表，未见本轮无条件注册赠额",
    reachability: "Chrome 2026-09-09 官网公开页和 /sign-up 可达；页面提供注册链接、模型列表、文档和价格表",
    note: "新发现的国产多模型统一 API 网关；公开页展示 OpenAI、DeepSeek、GLM、Kimi、Qwen、MiniMax 等模型价格。V2EX 帖子称 DeepSeek V4.1 Flash API 上线；未注册、未使用 API key，价格和模型库存以官网当前页面为准。",
    source: "TokenRa 官网 https://tokenra.io/zh/；V2EX 2026-09-09 主题 https://v2ex.com/t/1240537；Chrome 公开页核验（2026-09-09）。",
    topicUrls: ["https://v2ex.com/t/1240537"], affiliate: false,
    modelProviders: ["openai", "deepseek", "zhipu", "moonshotai", "qwen", "minimax"],
    offerLabelOverride: "按量计费 / 价格待核", offerKindOverride: "paid", ratingOverride: 3,
    updatedAt: "2026-09-09", verified: "2026-09-09 Chrome 官网及 /sign-up 复核 + Searchix V2EX 线索"
  },
  {
    id: "aff-fengshao",
    name: "Fengshao API",
    url: "https://api.fengshao1227.com/",
    domain: "api.fengshao1227.com",
    group: "公益站", category: "通用 API", status: "conditional", statusLabel: "注册路径待核",
    registration: "公开首页提供 Console / Sign in；注册入口未在本轮公开页独立定位",
    registrationGuide: "Chrome 2026-09-09 公开页可达，页面提供 Console 和 Sign in；未登录、未提交表单，注册条件待站方入口确认。",
    quota: "按量计费与实时用量监控；未确认免费额度或签到福利",
    reachability: "Chrome 2026-09-09 官网公开页可达；统一 API、模型广场、状态页和价格入口可见",
    note: "新发现的统一 AI API 网关，公开页列出 OpenAI、Claude、Gemini、DeepSeek、Qwen、Llama 等能力，并展示 OpenAI/Claude/Gemini 兼容路由和多区域部署说明；页面示例为公开演示数据，不等于账号可调用。",
    source: "Fengshao API 官网 https://api.fengshao1227.com/；LinuxDo 2026-09-09 主题 https://linux.do/t/topic/2878282；Chrome 公开页核验（2026-09-09）。",
    topicUrls: ["https://linux.do/t/topic/2878282"], affiliate: false,
    modelProviders: ["openai", "anthropic", "google", "deepseek", "qwen", "meta"],
    offerLabelOverride: "按量计费 / 福利待核", offerKindOverride: "paid", ratingOverride: 3,
    updatedAt: "2026-09-09", verified: "2026-09-09 Chrome 官网核验 + Searchix LinuxDo 线索"
  },
  {
    id: "aff-soleapi",
    name: "SoleAPI",
    url: "https://soleapi.com/",
    domain: "soleapi.com",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "Google/GitHub 授权登录或公开注册；活动按帖子规则参与",
    quota: "LINUX DO 账号注册送 $1；评论并加群再送 $5；固定福利每人一次，额度仅供体验",
    reachability: "官网公开页可抽取；LinuxDo 2026-09-07 主题提供新站活动",
    note: "多模型统一网关，官网公开支持 OpenAI、Anthropic 等协议并提供路由、限流、计费和数据遮蔽说明；当前未使用 API key 做模型调用测试，试用额度和实际库存待核。",
    source: "SoleAPI 官网 https://soleapi.com/；LinuxDo 2026-09-07 主题 2866001。",
    topicUrls: ["https://linux.do/t/topic/2866001"], affiliate: false,
    offerLabelOverride: "注册 $1 + 社群 $5（帖子称）", offerKindOverride: "community", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Chrome 读取 LinuxDo 主题 + Searchix 官网抽取"
  },
  {
    id: "aff-rsiai",
    name: "RSI AI",
    url: "https://www.rsiai.net/",
    domain: "www.rsiai.net",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "公开注册；充值后创建 API key",
    quota: "首充双倍到账（LinuxDo 活动帖称）；官网按模型 Token 计费，活动和余额待核",
    reachability: "官网注册页和文档可抽取；LinuxDo 2026-09-08 主题提供新站活动",
    note: "官网文档称提供 Claude、GPT 等模型的统一接口，先注册、充值、创建 key 再调用；首充双倍、5%-15%价格和具体模型库存来自活动宣传，尚未独立 API 核验。",
    source: "RSI AI 官网 https://www.rsiai.net/ 与文档 https://www.rsiai.net/docs；LinuxDo 2026-09-08 主题 2873002。",
    topicUrls: ["https://linux.do/t/topic/2873002"], affiliate: false,
    offerLabelOverride: "首充双倍（帖子称）", offerKindOverride: "paid", ratingOverride: 2, updatedAt: "2026-09-09", verified: "2026-09-09 Chrome 读取 LinuxDo 主题 + Searchix 官网抽取"
  },
  {
    id: "aff-linkagi",
    name: "LinkAGI",
    url: "https://api.linktoagi.com/",
    domain: "api.linktoagi.com",
    group: "付费站点", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "邮箱验证注册；无需 ChatGPT 账号",
    quota: "注册赠 ¥0.2 试用额度；最低充值和价格以实时页面为准",
    reachability: "V2EX 2026-09-09 主题；官网文档状态页可抽取",
    note: "面向 Codex、Claude Code、Gemini CLI 的统一 API 服务；官方状态页明确无 key 的 401 只证明鉴权入口响应，不证明模型可用，当前未进行授权 API 调用。",
    source: "V2EX 2026-09-09 主题 1240157；LinkAGI 状态页 https://docs.linktoagi.com/status.html。",
    topicUrls: ["https://www.v2ex.com/t/1240157"], affiliate: false,
    offerLabelOverride: "注册赠 ¥0.2", offerKindOverride: "trial", ratingOverride: 3, updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 抽取 V2EX 与官方文档"
  },
  {
    id: "aff-nexavlinks",
    name: "NexaVlinks",
    url: "https://www.nexavlinks.com/",
    domain: "www.nexavlinks.com",
    group: "付费站点", category: "通用 API", status: "conditional", statusLabel: "需条件",
    registration: "LINUX DO OAuth；帖子称 TL1 才能 OAuth，Cloudflare 拦截时需联系管理员",
    quota: "试营业：LINUX DO OAuth 送 2 额度至 2026-09-10 12:00；前 200 位评论另送 10 额度",
    reachability: "LinuxDo 2026-09-08 主题；官网域名由主题明确给出，未独立注册核验",
    note: "当前只提供 GPT Astra/Sol 全 Pro 号池；帖子自述不保证完全不降智、部分账号有风控，且订阅才能解锁低价分组。福利和稳定性均按商业活动处理。",
    source: "LinuxDo 2026-09-08 主题 2873976。",
    topicUrls: ["https://linux.do/t/topic/2873976"], affiliate: false,
    offerLabelOverride: "试营业 2 额度 / 前 200 送 10", offerKindOverride: "community", ratingOverride: 2, updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 抽取 LinuxDo 主题"
  },
  {
    id: "aff-inception-mercury",
    name: "Inception Mercury 2.5",
    url: "https://platform.inceptionlabs.ai/",
    domain: "platform.inceptionlabs.ai",
    group: "福利羊毛", category: "通用 API", status: "direct", statusLabel: "可直接注册",
    registration: "官方平台注册；登录后创建 API key",
    quota: "LinuxDo 2026-09-09 帖子称 Mercury 2.5 可免费使用；官方文档列有 Token 价格，免费额度和有效期以控制台为准",
    reachability: "官方官网、文档和平台公开入口可达",
    note: "Inception Labs 官方 API，Mercury 2.5 兼容 OpenAI Chat Completions；社区帖子中的免费额度属于活动线索，不作为长期承诺，正式使用前先核对控制台和账单规则。",
    source: "Inception 官方官网 https://www.inceptionlabs.ai/；官方文档 https://docs.inceptionlabs.ai/get-started；LinuxDo 2026-09-09 主题 2876708。",
    topicUrls: ["https://linux.do/t/topic/2876708"], affiliate: false,
    modelProviders: [],
    offerLabelOverride: "Mercury 2.5 免费体验（帖子称）", offerKindOverride: "free", ratingOverride: 3,
    updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 检索 + 官方官网/文档 HTTP 200 核验"
  }
];

window.AFFILIATE_OVERRIDES = {
  "公益站-1": {
    affiliateUrl: "https://anyrouter.top/register?aff=ZZ16", affiliate: true, mainlandAccess: "restricted",
    group: "公益站", quota: "注册 $100；签到 $25/天", pricing: "Opus 5 参考：输入 $5/M，输出 $25/M（可能变动）",
    registration: "GitHub 或邮箱注册",
    registrationGuide: "按注册页提示使用 GitHub 或邮箱完成注册；若遇 Cloudflare 验证，请在普通浏览器完成安全验证。",
    note: "本轮有效 key 仅列出 12 个 Claude，最高为 claude-opus-4-7 和 claude-fable-5-1；未见 claude-opus-5 或 claude-sonnet-5。四星评价不等同于最新 Claude 覆盖，冲最新模型前应先核对库存。",
    source: "用户提供（2026-09-06 API 模型列表实测）：Any Router 12 个 Claude，未见 Opus 5 或 Sonnet 5。",
    ratingOverride: 4, recommendationRank: 9, updatedAt: "2026-09-06", verified: "2026-09-06 用户 API 模型列表实测"
  },
  "高级推广-19": { affiliateUrl: "https://kuaipao.ai/register?aff=3uhI", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 11, verified: "2026-09-02 用户补充" },
  "高级推广-18": { affiliateUrl: "https://www.jiji.cc/register?aff=SB2HXSGR8PAG", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 12, verified: "2026-09-02 用户补充" },
  "高级推广-17": { affiliateUrl: "https://4router.net/register?aff=Rk7W", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 13, verified: "2026-09-02 用户补充" },
  "高级推广-7": {
    registration: "邮箱注册；LINUX DO 授权登录可参与当前活动",
    quota: "新用户注册 $3.8（LINUX DO 授权登录，帖子称）；首充 $66→$200 或 $119→$335 套餐，额度分区且有期限",
    topicUrls: ["https://linux.do/t/topic/2722570", "https://linux.do/t/topic/2734393", "https://linux.do/t/topic/2784996", "https://linux.do/t/topic/2875254"],
    note: "2026-09-09 活动帖称 GPT-6 Astra、Claude Fable 5.1 已上线；新用户注册赠额和首充套餐属于活动批次，套餐库存、有效期与分区限制以页面为准。此前有效 key 可列出 14 个 Claude，含 Opus 5、Sonnet 5、Fable 5.1，但不等于当前所有账号可见。",
    source: "LinuxDo 2026-09-08 主题 2875254；2026-09-06 API 模型列表实测：CUN.ai 14 个 Claude，含 Opus 5、Sonnet 5、Fable 5.1。",
    updatedAt: "2026-09-09", verified: "2026-09-09 Chrome/搜索核验 LinuxDo 更新帖 + 2026-09-06 API 模型列表实测"
  },
  "富可敌国-21": {
    topicUrls: ["https://linux.do/t/topic/2704400", "https://linux.do/t/topic/2783944", "https://www.v2ex.com/t/1240490"],
    registration: "公开注册；历史 LINUX DO 新用户赠额和邀请活动已结束，当前使用需充值",
    quota: "充值后 GPT/Grok 0.4x；Claude（Kiro）0.8x；充值赠余额档位和活动以站内页面为准",
    note: "2026-09-09 V2EX 更新称 GPT 线路恢复、GPT-6 Astra 和 Grok 上线、Claude Kiro 缓存恢复；历史新用户 $20 与邀请活动不再作为当前福利。",
    source: "V2EX 2026-09-09 主题 1240490；历史 LinuxDo 主题 2704400、2783944。",
    updatedAt: "2026-09-09", verified: "2026-09-09 Searchix 抽取 V2EX 更新帖"
  },
  "富可敌国-24": {
    affiliateUrl: "https://pqh.ai/sign-up?aff=iYIi", affiliate: true, offerLabelOverride: "回帖 / 进群 $8", offerKindOverride: "community", recommendationRank: 14,
    registration: "邀请链接注册；回帖 ID 并进入官方群后领取活动额度", quota: "当前帖称回帖进群送 $8；更高活动额度以当期公告为准",
    note: "近 3 天仍有运营主题，但福利依赖回帖和进群，不是注册即送。本轮有效 key 可列出 12 个 Claude，含 claude-opus-5、claude-sonnet-5、claude-fable-5 和 claude-fable-5-1。", source: "用户提供（2026-09-06 API 模型列表实测）：PQH 12 个 Claude，含 Opus 5、Sonnet 5、Fable 5 与 Fable 5.1。", updatedAt: "2026-09-06", verified: "2026-09-06 用户 API 模型列表实测"
  },
  "高级推广-8": { affiliateUrl: "https://api.wxiai.com/register?aff=BeNL", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 15, verified: "2026-09-02 用户补充" },
  "高级推广-23": { affiliateUrl: "https://aixoras.com/register?aff=h87n", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 16, verified: "2026-09-02 用户补充" },
  "富可敌国-22": { affiliateUrl: "https://api.axis.fan/register?aff=MP6BS9UELPVH", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 17, verified: "2026-09-02 用户补充" },
  "高级推广-21": {
    affiliateUrl: "https://88996api.cloud/register?aff=7p47", affiliate: true, offerLabelOverride: "回帖 / 联系 $10", offerKindOverride: "community", recommendationRank: 18,
    registration: "邀请链接注册；在活动帖留言后联系站方领取", quota: "当前活动为注册 + 回帖 + 联系后领取 $10；非自动到账",
    note: "近期活动明确要求回帖并联系站方，不能再标作“注册即送 $0.5”。", source: "LinuxDo 2026-08-15 主题：新用户注册加帖子留言，联系站方领取 $10。", verified: "2026-09-03 LinuxDo 复核"
  },
  "高级推广-2": { affiliateUrl: "https://new.xychatai.com/pastel#/register?i=f2jmk", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 19, verified: "2026-09-02 用户补充" },
  "富可敌国-1": { affiliateUrl: "https://torchai.ai/sign-up?aff=cbbz", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 20, verified: "2026-09-02 用户补充" },
  "高级推广-24": {
    affiliateUrl: "https://gateai.cc/register?aff=RHPV65NMCBJL", affiliate: true, offerLabelOverride: "最高 $10", offerKindOverride: "community", recommendationRank: 22,
    registration: "LinuxDo 注册；回帖用户名并首次进群", quota: "注册 $2；回帖 $3；首次进群 $5；合计最高 $10",
    note: "当前活动由三个步骤组成，回帖和进群奖励不能视为自动注册赠额。", source: "LinuxDo 2026-09-01 主题：注册 $2、回帖 $3、进群 $5，合计最高 $10。", verified: "2026-09-03 LinuxDo 复核"
  },
  "公益站-2": {
    affiliateUrl: "https://windhub.cc/register?aff=LGsr", affiliate: true, offerLabelOverride: "限量注册码", offerKindOverride: "community", recommendationRank: 23,
    registration: "限量注册码注册；通过 LDC 或站方不定期发码获取", quota: "无已承诺的固定白票；签到与当日额度以控制台规则为准",
    note: "8 月底仍持续维护模型与可用率；注册曾按批次发放 100 个免费码，非永久公开注册。", source: "LinuxDo 2026-08-29 更新帖：公布模型状态页并曾开放 100 个注册码，后续可能调整签到与风控。", verified: "2026-09-03 LinuxDo 复核"
  },
  "公益站-11": { affiliateUrl: "https://x666.me/register?aff=kydZ", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 24, verified: "2026-09-02 用户补充" },
  "高级推广-34": { affiliateUrl: "https://api.nexaix.net/sign-up?aff=Hoq3", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 25, verified: "2026-09-02 用户补充" },
  "福利羊毛-6": { affiliateUrl: "https://itokens.io?invite_code=csWg2TpF", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 26, verified: "2026-09-02 用户补充" },
  "公益站-21": { affiliateUrl: "https://ai.centos.hk/register?aff=qMJJ", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 28, verified: "2026-09-02 用户补充" },
  "公益站-25": { category: "工具 / 服务", note: "开源影视/短剧创作工作台，在线端用于体验与反馈；正式私有素材建议自行部署。积分来自签到、有效反馈或购买 CDK。", source: "LinuxDo 2026-07-27 站方主题：影策开源工作台，说明每日签到、反馈奖励和 CDK 购买积分规则。", verified: "2026-09-04 LinuxDo 复核" },
  "高级推广-9": { note: "近期退款/封号争议中，站方说明退款按“充值-赠金-消耗”计算，且承认风控可能误封；不将历史签到作为当前福利。", source: "LinuxDo 2026-08-08 站方公开回应退款与封号问题。", verified: "2026-09-04 LinuxDo 风险复核" },
  "公益站-6": { affiliateUrl: "https://ai.121628.xyz/sign-up?aff=Mnud", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 29, verified: "2026-09-02 用户补充" },
  "高级推广-28": { affiliateUrl: "https://yiapi.ai/register?aff=6DJQPZQRKDCA", affiliate: true, recommendationRank: 30, ratingOverride: 0, browserHidden: true, note: "LinuxDo 近期出现充值后账号被删、无法登录且客服未回应的完整用户反馈；停止推荐。", source: "LinuxDo 2026-08-10 反馈帖：用户称充值后次日接口频繁报错、无法登录、账号被删且客服未回应；多名跟帖提示风险。", verified: "2026-09-03 LinuxDo 风险复核" },
  "公益站-16": { affiliateUrl: "https://ai.prism.uno/sign-up?aff=6S59", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 31, verified: "2026-09-02 用户补充" },
  "高级推广-25": { affiliateUrl: "https://dddai.dev/sign-up?aff=FBye", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 32, verified: "2026-09-02 用户补充" },
  "公益站-8": { affiliateUrl: "https://new-api.abrdns.com/register?aff=oDoU", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 33, verified: "2026-09-02 用户补充" },
  "公益站-14": {
    affiliateUrl: "https://api.coee.ccwu.cc/register?aff=6VB1", affiliate: true, offerLabelOverride: "签到 $3", offerKindOverride: "affiliate", recommendationRank: 34,
    quota: "签到 $3", note: "用户补充：签到 $3；注册门槛及到账规则仍以当前控制台为准。", source: "报告记录；用户补充：CoeeApi 邀请注册链接，签到 $3。", verified: "2026-09-02 用户补充"
  },
  "公益站-3": { affiliateUrl: "https://elysiver.h-e.top/sign-up?aff=6VPJ", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 35, verified: "2026-09-02 用户补充" },
  "公益站-31": { affiliateUrl: "https://luckyg.131518.xyz/sign-up?aff=M4xt", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 36, verified: "2026-09-02 用户补充" },
  "公益站-41": { affiliateUrl: "https://runanytime.hxi.me/register?aff=t8aZ", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 37, verified: "2026-09-02 用户补充" },
  "高级推广-32": {
    affiliateUrl: "https://cdn.coderelay.cn/sign-up?aff=uzZD", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 38,
    registration: "开放注册；支持邮箱、QQ 邮箱与 Linux.do 登录，具体流程以注册页为准", note: "用户补充：开放注册、支持 QQ 邮箱和 Linux.do；原有试用规则以控制台为准。", source: "报告记录；用户补充：CodeRelay 开放注册，支持邮箱、QQ 邮箱、Linux.do。", verified: "2026-09-02 用户补充"
  },
  "高级推广-9": { affiliateUrl: "https://sui-xiang.com/register?aff=CW6PBFXPCJYV", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 39, verified: "2026-09-02 用户补充" },
  "高级推广-35": { affiliateUrl: "https://modelflare.dev/sign-up?aff=LVrn", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 41, verified: "2026-09-02 用户补充" },
  "高级推广-29": { affiliateUrl: "https://www.fastaitoken.com/register?aff=CJQK5ETSM6N9", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 42, verified: "2026-09-02 用户补充" },
  "公益站-46": { affiliateUrl: "https://47-gpt.com/register?aff=RHAUCUTUEVSA", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", recommendationRank: 43, verified: "2026-09-02 用户补充" },
  "富可敌国-18": {
    affiliateUrl: "https://fluxionai.space/register?aff=7LGADR78BFJS", affiliate: true, offerLabelOverride: "签到 / 邀请", offerKindOverride: "affiliate", recommendationRank: 44,
    registration: "通过邀请链接注册；加入官方 QQ 群，在置顶公告填写接头暗号可得 $0.3", quota: "每日签到随机福利余额；首调 Fluxion API 得 $0.5；提交问卷得 $0.2；首次充值/订阅按 5%-20% 阶梯加赠",
    note: "连续签到第 7/15/30 天有额外礼包，断签清零且不可补签；首次充值/订阅单账号一次，最高加赠 20U。", source: "报告记录；用户补充：FluxionAI 邀请链接、签到、群暗号、首调、问卷与首充阶梯加赠规则。", verified: "2026-09-02 用户补充"
  },
  "公益站-5": { quota: "新账号先完成签到后逐步解锁权限；奖励金额未公开", note: "近期论坛说明新账号初始仅有签到权限，达到签到条件后转为完整账号；站内游戏与邀请码规则会变动。", source: "LINUX DO 近期站方说明：新账号先签到，满足条件后解锁完整权限。", verified: "2026-09-03 LINUX DO" },
  "公益站-6": { affiliateUrl: "https://ai.121628.xyz/sign-up?aff=Mnud", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", note: "近期反馈仍可使用 DeepSeek、MiniMax、GLM 等免费分组；未见固定注册赠额规则。", source: "LINUX DO 2026-08-24 至 09-03 使用反馈。", verified: "2026-09-03 LINUX DO" },
  "公益站-17": { note: "近期有 GPT 端点 401、频道暂不可用的反馈；不将历史首次额度视为当前权益。", source: "LINUX DO 2026-08-29 使用反馈。", verified: "2026-09-03 LINUX DO" },
  "公益站-22": { note: "当前为 Grok Free 共用池，设有动态并发和限流；站方明确无充值、无邀请的固定福利。", source: "LINUX DO 2026-09-02 至 09-03 站方与使用反馈。", verified: "2026-09-03 LINUX DO" },
  "高级推广-27": { affiliateUrl: "https://www.fuxingapi.com/sign-up?aff=idcL", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", note: "本轮有效 key 可列出 8 个 Claude，含 claude-opus-5 与 claude-sonnet-5。", source: "用户提供（2026-09-06 API 模型列表实测）：福星 AI 8 个 Claude，含 Opus 5 与 Sonnet 5。", updatedAt: "2026-09-06", verified: "2026-09-06 用户 API 模型列表实测" },
  "富可敌国-6": { affiliateUrl: "https://api.oaipro.com/register?aff=huE8em", affiliate: true, offerLabelOverride: "邀请入口", offerKindOverride: "unknown", verified: "2026-09-04 用户补充" },
  "公益站-23": { note: "近期只面向 LINUX DO 1 级用户开放，2 级才可签到；当前注册已收口，历史兑换码与 $5 不作为现行规则。", source: "LINUX DO 2026-08-15 至 08-22 站方说明。", verified: "2026-09-03 LINUX DO" },
  "公益站-32": { status: "closed", statusLabel: "服务已关闭", browserHidden: true, note: "近期维护/关闭汇总已列为关闭，不再展示历史重置额度。", source: "LINUX DO 2026-08-30 维护关闭记录。", verified: "2026-09-03 LINUX DO" },
  "高级推广-3": { status: "closed", statusLabel: "官网不可用", browserHidden: true, note: "近期反馈官网无法打开，默认隐藏等待恢复。", source: "LINUX DO 2026-09-03 反馈帖。", verified: "2026-09-03 LINUX DO" },
  "高级推广-15": { status: "closed", statusLabel: "安全风险", browserHidden: true, note: "近期多条反馈指向设备标识同步与强制插件行为的隐私/安全风险，不作为可推荐站点展示。", source: "LINUX DO 2026-08-28 至 08-31 讨论。", verified: "2026-09-03 LINUX DO" },
  "公益站-13": { status: "closed", statusLabel: "仅存量用户", browserHidden: true, note: "签到与充值已关闭，近期没有新注册或恢复服务的证据；旧用户亦有低速、不可用反馈。", source: "LINUX DO 2026-08 至 09 近期反馈。", verified: "2026-09-03 LINUX DO" },
  "公益站-52": { status: "closed", statusLabel: "当前未开放", browserHidden: true, note: "近期仅能确认上一轮限量开放与历史余额恢复，未见当前可用注册规则。", source: "LINUX DO 2026-08-17 站方说明。", verified: "2026-09-03 LINUX DO" },
  "公益站-51": { status: "closed", statusLabel: "非 AI API", browserHidden: true, note: "该条目为节点订阅服务，不属于本站收录范围的 AI API 或 AI 工具。", source: "LINUX DO 2026-09-02 主帖说明。", verified: "2026-09-03 人工归类" },
  "高级推广-1": { status: "closed", statusLabel: "非 AI 服务", browserHidden: true, note: "数字商品渠道，未提供可核实的 AI 服务或 API 规则。", source: "人工复核：原条目说明。", verified: "2026-09-03 人工归类" },
  "高级推广-4": { status: "closed", statusLabel: "非 AI 服务", browserHidden: true, note: "主机服务，未提供可核实的 AI 服务或 API 规则。", source: "人工复核：原条目说明。", verified: "2026-09-03 人工归类" },
  "高级推广-5": { status: "closed", statusLabel: "非 AI 服务", browserHidden: true, note: "VPN 服务，未提供可核实的 AI 服务或 API 规则。", source: "人工复核：原条目说明。", verified: "2026-09-03 人工归类" },
  "高级推广-6": { status: "closed", statusLabel: "非 AI 服务", browserHidden: true, note: "基础设施服务，未提供可核实的 AI 服务或 API 规则。", source: "人工复核：原条目说明。", verified: "2026-09-03 人工归类" },
  "高级推广-14": { status: "closed", statusLabel: "非 AI 服务", browserHidden: true, note: "短信服务，未提供可核实的 AI 服务或 API 规则。", source: "人工复核：原条目说明。", verified: "2026-09-03 人工归类" },
  "高级推广-13": { status: "closed", statusLabel: "当前未开放", browserHidden: true, note: "只有早期营销和抽奖记录，未见当前可用服务或注册规则。", source: "LINUX DO 历史帖子复核。", verified: "2026-09-03 LINUX DO" },
  "高级推广-18": { status: "closed", statusLabel: "当前未开放", browserHidden: true, note: "未找到可核实的当前注册入口、额度或服务状态。", source: "LINUX DO 近期检索复核。", verified: "2026-09-03 LINUX DO" },
  "富可敌国-11": { status: "closed", statusLabel: "当前未开放", browserHidden: true, note: "未见可用注册表单或近期可核实服务规则。", source: "LINUX DO 近期检索复核。", verified: "2026-09-03 LINUX DO" },
  "富可敌国-12": { status: "closed", statusLabel: "当前未开放", browserHidden: true, note: "未见可用注册表单或近期可核实服务规则。", source: "LINUX DO 近期检索复核。", verified: "2026-09-03 LINUX DO" },
  "福利羊毛-8": { url: "https://image.mlgb7.com/login", status: "conditional", statusLabel: "需 LINUX DO 登录", registration: "迁移至 image.mlgb7.com，使用 LINUX DO Connect", quota: "注册 500 积分；签到 100-300 积分/天；生成一张图消耗 10 积分", note: "服务已迁移并在 8 月 29 日恢复；仅 image-2 1k，图片保留 36 小时。", source: "LINUX DO 2026-08-15 主帖及 08-29 恢复公告。", verified: "2026-09-03 LINUX DO" },
  "高级推广-31": { status: "closed", statusLabel: "服务调整中", browserHidden: true, note: "平台公告称自 2026-08-31 起进行服务调整，部分内容与功能暂不可访问。", source: "用户补充：魔芋 AI 2026-08-31 起服务调整。", verified: "2026-09-02 用户补充" },
  "福利羊毛-2": { status: "closed", statusLabel: "活动已结束", browserHidden: true, note: "用户补充：官方活动已结束，不再作为当前可领取福利展示。", source: "报告记录；用户补充：活动已结束。", verified: "2026-09-02 用户补充" },
  "公益站-4": { status: "closed", statusLabel: "当前不可达", browserHidden: true, note: "用户补充：上游已停止服务。", source: "报告记录；用户补充：上游应该是拉闸了。", verified: "2026-09-02 用户补充" },
  "公益站-7": { status: "closed", statusLabel: "暂不可用", browserHidden: true, note: "用户补充：服务暂时不可用。", source: "报告记录；用户补充：This service is temporarily unavailable。", verified: "2026-09-02 用户补充" },
  "公益站-15": { status: "closed", statusLabel: "当前不可达", browserHidden: true, registration: "注册仅支持 QQ 邮箱；当前入口返回 Error 530", note: "用户补充：入口返回 Error 530，默认隐藏等待恢复。", source: "报告记录；用户补充：Error 530，注册仅支持 QQ 邮箱。", verified: "2026-09-02 用户补充" },
  "公益站-18": { status: "closed", statusLabel: "当前不可达", browserHidden: true, registration: "注册仅支持 GitHub；当前入口返回 Error 555", note: "用户补充：入口显示 all down / Error 555，默认隐藏等待恢复。", source: "报告记录；用户补充：Error 555，注册仅支持 GitHub。", verified: "2026-09-02 用户补充" },
  "公益站-35": { status: "closed", statusLabel: "当前不可达", browserHidden: true, registration: "注册仅支持 Linux.do；当前入口返回 403", note: "用户补充：入口返回 403，默认隐藏等待恢复。", source: "报告记录；用户补充：403 Forbidden，注册仅支持 Linux.do。", verified: "2026-09-02 用户补充" },
  "公益站-40": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "本轮实测非浏览器 API 客户端返回 Cloudflare Just a moment... 挑战页，无法完成 API 调用；公开入口受 Cloudflare 拦截的既有记录保留。", source: "用户提供（2026-09-06 API 实测）：42 API 对非浏览器客户端返回 Cloudflare 挑战页。", updatedAt: "2026-09-06", verified: "2026-09-06 用户 API 实测" },
  "公益站-43": { status: "closed", statusLabel: "当前不可达", browserHidden: true, note: "用户补充：Web server is down，Error 521。", source: "报告记录；用户补充：Error 521。", verified: "2026-09-02 用户补充" },
  "公益站-27": { status: "closed", statusLabel: "维护中", browserHidden: true, note: "用户补充：系统维护进行中，站方称当前暂停服务。", source: "报告记录；用户补充：系统维护进行中。", verified: "2026-09-02 用户补充" },
  "高级推广-20": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：站点在当前所在地区暂不可访问。", source: "报告记录；用户补充：所在地区暂不可访问。", verified: "2026-09-02 用户补充" },
  "富可敌国-14": { status: "closed", statusLabel: "当前不可达", browserHidden: true, note: "用户补充：当前无法访问，默认隐藏等待恢复。", source: "报告记录；用户补充：无法访问此网站。", verified: "2026-09-02 用户补充" },
  "公益站-34": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：公开入口被 Cloudflare 拦截。", source: "报告记录；用户补充：Cloudflare 拦截。", verified: "2026-09-02 用户补充" },
  "公益站-39": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：公开入口被 Cloudflare 拦截。", source: "报告记录；用户补充：Cloudflare 拦截。", verified: "2026-09-02 用户补充" },
  "高级推广-26": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：站点不向中国大陆地区提供服务。", source: "报告记录；用户补充：不向中国大陆地区提供服务。", verified: "2026-09-02 用户补充" },
  "高级推广-11": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：站点不向中国大陆地区提供服务。", source: "报告记录；用户补充：不向中国大陆地区提供服务。", verified: "2026-09-02 用户补充" },
  "公益站-50": { mainlandAccess: "restricted", status: "conditional", statusLabel: "限定注册", note: "用户补充：公开入口被 Cloudflare 拦截。", source: "报告记录；用户补充：Cloudflare 拦截。", verified: "2026-09-02 用户补充" },
  "福利羊毛-1": { registration: "AMD 开发者平台活动页领取", quota: "每日免费 600M；支持 DeepSeek-V4-Flash、GLM-5.3-Flash、Qwen3.8-Flash-Next", note: "每日 600M 免费调用；超出当日免费量后的规则以活动页为准。", source: "用户截图（2026-09-03）：AMD 开发者平台每日免费 600M，支持 DeepSeek-V4-Flash、GLM-5.3-Flash、Qwen3.8-Flash-Next。", verified: "2026-09-03 用户截图" }
};
